version: '2'
networks:
    rewire:
        driver: bridge
services:
    nginx:
        image:
            nginx
        networks:
            - rewire
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/log/:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/app/nginx.conf:/app/nginx.conf
            - ./nginx/html:/var/html
            - ./nginx/app:/app

    web:
        build:
            ./web/
        networks:
            - rewire







