version: '2'
networks:
     vpcbr:
        driver: bridge
        ipam:
         config:
           - subnet: 10.5.0.0/16
             gateway: 10.5.0.1

services:
    nginx:
        image:
            nginx
        container_name: nginx-proxy
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/log/:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/app/nginx.conf:/app/nginx.conf
            - ./nginx/html:/var/html
            - ./nginx/app:/app
        links:
            - piwik:piwik
        depends_on:
            - piwik

    piwik:
        image:
            carwestsam/connect-piwik
        container_name:
            piwik
        networks:
            vpcbr:
                ipv4_address: 10.5.0.5

    mysql:
        image:
            mysql:8
        container_name:
            database
        environment:
            - MYSQL_ROOT_PASSWORD
        networks:
          vpcbr:
            ipv4_address: 10.5.0.6
        ports:
            - "3360:3360"







